on: pull_request

name: Pull Request

jobs:
  message-check:
    name: Block Autosquash Commits

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.4.0

      - name: Block Autosquash Commits
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
